spring.profiles.active=local
#spring.profiles.active=prod

spring.application.name=petcare

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# JSP 사용 시 (Thymeleaf 미사용)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 파일 업로드
file.upload-dir=C:/upload/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===== MyBatis =====
mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
# type-aliases-package는 Controller 등과 이름 충돌 가능 → XML에서 VO 전체 경로 사용 또는 VO에 @Alias

# api-key
kakao.rest-api-key=17a2a2e64e3ea96800eea45eb33cc90a
kakao.js-api-key=9dd4881b6589cf4c0fa61514aff5ff80
abandonmentPublic-api-key=2b51e632efe531f6be118d63888e287e0588445a805a7b48fba2d090c9e3c526
toss.client-key=test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm