spring.profiles.active=local
#spring.profiles.active=prod

spring.application.name=petcare

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# JSP 사용 시 (Thymeleaf 미사용)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 파일 업로드
file.upload-dir=C:/upload/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===== MyBatis =====
mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
# type-aliases-package는 Controller 등과 이름 충돌 가능 → XML에서 VO 전체 경로 사용 또는 VO에 @Alias

# api-key
kakao.rest-api-key=17a2a2e64e3ea96800eea45eb33cc90a
kakao.js-api-key=9dd4881b6589cf4c0fa61514aff5ff80
public.service-api-key=3ea2006efec59c8f8d86043a4d623f6bcde7740bf4ba6bb70f788fbc55923bb4
toss.client-key=test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm